### ISSUE TITLE
403

### ISSUE THREAD

**Issue by barajus** [benrules2/losemoneybot#1]
Hey man,
I just filled username and password with my credentials, but I'm getting this : 

Traceback (most recent call last):
  File "PinnacleBetBot.py", line 108, in <module>
    balance = get_balance(base_url, username, password)
  File "PinnacleBetBot.py", line 14, in get_balance
    responseData = ulib.urlopen(req).read()
  File "/usr/lib/python3.2/urllib/request.py", line 139, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 376, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 488, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 414, in error
    return self._call_chain(_args)
  File "/usr/lib/python3.2/urllib/request.py", line 348, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.2/urllib/request.py", line 496, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by benrules2** [comment]
Hey,

Two thoughts on what it could be. First of all, Pinnacle specifies you need to have funds in your account to use the API. So if you haven't made a deposit, then it might just be blocked.

Secondly, username and password need to be surrounded by quotes. I'm going to push a change so that is more obvious.

Let me know how that goes for you.

**Comment by barajus** [comment]
Thank for your answer. 
Indeed, I did not transfer money yet. 
I'm going to do it and check again !

**Comment by barajus** [comment]
Now I have this error, but I guess that's another problem.

Traceback (most recent call last):
  File "PinnacleBetBot.py", line 110, in <module>
    bet = find_bet(odds)
  File "PinnacleBetBot.py", line 41, in find_bet
    for l in k['moneyline'].keys():
KeyError: 'moneyline'

**Comment by benrules2** [comment]
Nice, so your balance worked. You're just getting an exception because the odds you pulled have no money line. I've added a try / except around that block - checkout the newest change.

Thanks for testing this out btw, I really appreciate it.

**Comment by barajus** [comment]
Yeah, balance is now working since I put money :)
I'll keep you in touch with other problems !

**Comment by benrules2** [comment]
Yo, I'm gonna close this just because we've sort of drifted. Thanks again for the trail run.
