### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by barajus** [benrules2/losemoneybot#2]
Hey man ✋ Hope you are doing well.

I'm getting a 403 now, when I try to connect to Pinnacle, do you have the same problem ?

`(none):~/losemoneybot# python3 PinnacleBetBot.py
Traceback (most recent call last):
  File "PinnacleBetBot.py", line 114, in <module>
    balance = get_balance(base_url, username, password)
  File "PinnacleBetBot.py", line 14, in get_balance
    responseData = ulib.urlopen(req).read()
  File "/usr/lib/python3.2/urllib/request.py", line 139, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 376, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 488, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 414, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 348, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 496, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

It looks like the pinnacle API was updated (25/11), but it doesn't suppose to break anything... any thoughts ?
Have a nice day

**Comment by benrules2** [comment]
Hey, good to hear from you again. Sorry to say everything worked fine for me. Tried on both Windows and Linux.

The only thing I can think of is maybe it's related to your python version. Looks like you're on 3.2, and I'm running 3.4 and 3.5. Maybe a problem on Pinnacle's side too.

**Comment by barajus** [comment]
Alright, I just wanted to check with you, sorry for the noise :)

**Comment by barajus** [comment]
Support :

Your API access was blocked due the frequency of calls/bandwidth usage and lack of wagering activity. The API is meant as a service for wagering and not data gathering. 
 
If you substantially increase your wagering activity over the next 3 months you may contact us at the end of that period to request to have your access enabled. Whether the wagering activity over that period is sufficient will be decided by us at that time.

**Comment by benrules2** [comment]
Damn, thanks for the update. I guess you have to place a certain number of bets to keep access alive. I lost enough money they haven't locked me out.

**Comment by barajus** [comment]
Haha !
I'm gonna place some bet then..
